### ISSUE TITLE
Styles not updating from 'my-doks-theme' with v1.0.0-rc.2

### ISSUE THREAD

**Issue by keybits** [gethyas/doks-core#24]
## Description

I'm using Doks [v1.0.0-rc.2](https://github.com/h-enk/doks/releases/tag/v1.0.0-rc.2)  and have copied `assets/scss/common/_variables.css` from `node_modules/@hyas/doks-core` to `themes/my-doks-theme/assets/scss/common/_variables.scss`. When I make changes the styles don't update.

I've double checked the values in `config/_default/module.toml` and they look correct.

### Steps to reproduce

Copy `assets/scss/common/_variables.scss` to `themes/my-doks-theme/assets/scss/common/_variables.scss` and make changes. These are not refelected on the frontend. If we change values in the `node_modeles` version of the file updates are reflected.

### Environment

Installed on 2023-07-22 with `npm create hyas@latest -- --template doks`

I realise this is a pre-release but hopefully the bug report is useful.

**Comment by h-enk** [comment]
You can add this file to an excludeFiles section in the appropriate place (doks-core) of the module mounts file. 

Bit cryptic,  but I hope it helps ( I' m on the go)

**Comment by keybits** [comment]
Aha! That works, thanks! (And thanks for your work on this 😄 )
