### ISSUE TITLE
Flexsearch 0.7.41 breaks search on new deployment

### ISSUE THREAD

**Issue by jollydodo** [gethyas/doks-core#84]
## Description

Noticed that the flex search functionality wasn't working after an automatic scheduled Netlify deploy. Confirmed that this was also the case with a new clean doks-install. 

### Steps to reproduce

1. clone Doks and run npm install
2. The problem shows with npm run dev and in the build versions
3. However, my local version still does some caching so the problem doesn't show here. Only on deployment or a new clone

### Expected result

Search bar should load on click. (will add the console error tomorrow. Currently fixed the problem in my deployment by going back to 0.7.31

### Actual result

no search bar shows up.

### Additional

I have some dynamic content on a new website (very simple stuff that checks for a date and removes events if the date has passed). Therefore the website redeploys every week on Netlify. However, I'm struggling with all these dependencies. I ran my personal Hugo portfolio for years on Hugo now, but that is a very simple website that gets updated very infrequently. I'm now really debating if a complex Hugo website with all these dependencies is able to keep this new website low maintenance ( I don't want to fix problems after each weekly redeploy since it's a website for an organisation where the people maintaining it don't necessarily are coders). Any tips for this? I'm open for suggestions :)

**Comment by h-enk** [comment]
Not sure if related, but FlexSearch (also) broke for me with the [latest version 0.7.31](https://github.com/nextapps-de/flexsearch/releases/tag/0.7.31)

I fixed my issue with https://github.com/gethyas/doks-core/pull/86/files#diff-817f7ddc38268fe8ecb65706db50973c273680c26f790b8a25ccf72d2c89c38f

I haven't tested this fix with [v0.7.43](https://www.npmjs.com/package/flexsearch) yet though

**Comment by h-enk** [comment]
Tested with 0.7.43 and the [import fix](https://github.com/gethyas/doks-core/pull/86/files#diff-817f7ddc38268fe8ecb65706db50973c273680c26f790b8a25ccf72d2c89c38f) works — for me

**Comment by h-enk** [comment]
Merged: https://github.com/gethyas/doks-core/pull/86
